boot.o: boot.S multiboot.h x86_desc.h types.h
int_handler.o: int_handler.S
x86_desc.o: x86_desc.S x86_desc.h types.h
file_system.o: file_system.c file_system.h lib.h types.h x86_desc.h \
  system_calls.h paging.h terminal.h keyboard.h i8259.h rtc.h \
  int_handler.h scheduler.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h x86_desc.h types.h lib.h int_handler.h system_calls.h \
  file_system.h paging.h terminal.h keyboard.h i8259.h rtc.h scheduler.h \
  mouse.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h int_handler.h system_calls.h file_system.h paging.h \
  terminal.h keyboard.h rtc.h scheduler.h mouse.h
keyboard.o: keyboard.c keyboard.h lib.h types.h i8259.h terminal.h \
  system_calls.h x86_desc.h file_system.h paging.h rtc.h int_handler.h \
  scheduler.h
lib.o: lib.c lib.h types.h terminal.h keyboard.h i8259.h paging.h \
  x86_desc.h system_calls.h file_system.h rtc.h int_handler.h scheduler.h
mouse.o: mouse.c mouse.h lib.h types.h i8259.h terminal.h keyboard.h \
  paging.h x86_desc.h system_calls.h file_system.h rtc.h int_handler.h \
  scheduler.h
paging.o: paging.c paging.h x86_desc.h types.h lib.h terminal.h \
  keyboard.h i8259.h system_calls.h file_system.h rtc.h int_handler.h \
  scheduler.h
rtc.o: rtc.c rtc.h lib.h types.h i8259.h system_calls.h x86_desc.h \
  file_system.h paging.h terminal.h keyboard.h int_handler.h scheduler.h
scheduler.o: scheduler.c scheduler.h lib.h types.h i8259.h system_calls.h \
  x86_desc.h file_system.h paging.h terminal.h keyboard.h rtc.h \
  int_handler.h
system_calls.o: system_calls.c system_calls.h lib.h types.h x86_desc.h \
  file_system.h paging.h terminal.h keyboard.h i8259.h rtc.h \
  int_handler.h scheduler.h
terminal.o: terminal.c terminal.h lib.h types.h keyboard.h i8259.h \
  paging.h x86_desc.h system_calls.h file_system.h rtc.h int_handler.h \
  scheduler.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h paging.h terminal.h \
  keyboard.h i8259.h system_calls.h file_system.h rtc.h int_handler.h \
  scheduler.h
